5.3 (#11)
* Add support for algo to send check-sync

* Allow additional characters for the name, content and details
- Allow additional characters
- Allow multi-lingual
- Use escape to keep it secure

* Update 400_recordings.xml

Add record_ext=wav to maintain original behavior, recording by default to a WAV file.

* Add ooma to decode the IP address

* Add recording insert_date

* Fix call center missed call

Fixed this by changing the order of operations.
Billsec greater than zero overrode missed call equal to true.

* Add escape_textarea for backwards compatibility

* Use a safer default

Change the default to 0.0.0.0 to 127.0.0.1

* Fix the user_uuid using database::new()

* Fix transactions to save the domain_uuid

Symptom
Advanced -> Transactions showed as global when it should have shown the correct domain. This was failing when saving a new record.

* Escape characters for button link (#7409)

* Prevent a count error

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given

* Create file_size.lua

* Set a threshold for a valid voicemail size

* Update extension_edit.php

Remove an SQL order by that is not needed

* Fix security vulnerability when using openai

- Security update required for those using text-to-speech with openai
- Improved overall sanitization of the filename
- Remove more characters with str_replace and 
- Use an array to define the characters to remove with str_replace.
- Add | and ` to the str_replace
- Added escapeshellarg for additional protection

* fix spelling mistake in xml_cdr method name

Change the method name from moved_to_failed to move_to_failed

* Update {$mac}.xml

* Fix the recording name

* Minor version update 5.3.9

* Fix TTA use waitsec

* Update xml_cdr_inc.php

---------

Co-authored-by: FusionPBX <markjcrane@gmail.com>
Co-authored-by: FusionPBX <mark@fusionpbx.com>
Co-authored-by: frytimo <tim@fusionpbx.com>